# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PHP-Session
version:      0.21
version_from: lib/PHP/Session.pm
installdirs:  site
requires:
    Test::More:                    0.32
    UNIVERSAL::require:            0.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
