---
abstract: 'read / write PHP session files'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PHP-Session
no_index:
  directory:
    - inc
    - t
requires:
  Test::More: 0
  UNIVERSAL::require: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/php-session.git
version: 0.27
